[project]
name = "decondemo"
version = "0.1.0"
description = "A demo package for DFT signal deconvolution."
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "matplotlib",
    "click",
]

[project.scripts]
decondemo = "decondemo.__main__:cli"
